# Generated by Django 6.0.3 on 2026-03-19 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pueblomagico',
            name='descripcion_historica',
        ),
        migrations.AddField(
            model_name='pueblomagico',
            name='descripcion_cultural',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pueblomagico',
            name='historia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pueblomagico',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pueblos/'),
        ),
        migrations.AddField(
            model_name='pueblomagico',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'producto')},
            },
        ),
    ]
