# Generated by Django 6.0.3 on 2026-03-20 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_remove_pueblomagico_descripcion_historica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto'),
        ),
    ]
